version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  db:
    image: postgres
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 

  app:
    container_name: laravel-app
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: 0innominate0/laravel_crud:v1
    ports:
      - "9000:8000"
    environment:
      DB_CONNECTION: postgresdb
      DB_HOST: host.docker.internal
      DB_PORT: 6543
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    working_dir: /var/www

volumes:
  db_data:
