version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    # restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_CONNECTION: postgresdb
      DB_HOST: db
      DB_PORT: 6543
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    container_name: postgres
    #restart: unless-stopped
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6543"
